# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install .NET Trace Tool
      run: dotnet tool install --global dotnet-trace
    - name: Authenticate with GitHub Packages
      run: dotnet nuget update source GitHub --username GitHub --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Restore Packages
      run: dotnet restore -p:Platform=x64 -p:Configuration=Release
    - name: Build Project
      run: dotnet build --no-restore -p:Platform=x64 -p:Configuration=Release
    - name: Show Tree
      run: tree -a $GITHUB_WORKSPACE
    - name: Test Project (with Tracing)
      run: dotnet-trace collect --providers Microsoft-Windows-DotNETRuntime:4 --show-child-io -- dotnet test --no-build --verbosity normal -p:Platform=x64 -p:Configuration=Release
    - name: Publish Traces
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: NativeLibraryProbing
        path: '**/*.nettrace'
